- src/main/scala/HeaderEnum.scala
- src/main/scala/SCR.scala
- src/main/scala/Util.scala
Adds some singletons to SCR.scala and a PutSeqDriver utility to be able to drive sequences of SCR configurations for TL unit tests. Needed for HBWIF.
> Add SCR features needed to test HBWIF

- .gitignore
- build.sbt
This is needed to build when testchipip is built outside of rocket-chip.
> Scala 2.12 build.sbt fix

- src/main/scala/Serdes.scala
Previous assertion was impossible to meet. This will still work assuming you don't create a full loop both on chip and off.
> make manager >= client sourceBits.

- csrc/blkdev.cc
- csrc/blkdev.h
This fixes a problem I'm seeing with gcc versions on the BWRC machines and inttypes.h.
> Fix PRIx64 problem with certain gcc versions

- src/main/resources/testchipip/vsrc/ClockUtil.v
The timescale directive isn't a local change so the propsed method avoids changing other bits of code which might rely on the default timescale.
> Fix periodchecker to not use timescale

- src/main/resources/testchipip/csrc/SimSerial.cc
Fesvr handles this now so just pass on the plusargs and
they will be correctly ignored
Fixes #34
> Don't do anything special with simserial args

- src/main/scala/Serdes.scala
Helps both top and testharness to respond to different parameter changes.
The default is the same value that is currently the default.
> Add sinkId parameter for integration

- src/main/scala/Switcher.scala
Single mBus multi-port switcher support
rocket-chip now uses a single mBus with multiple nested ports for multiple memory channels so the canonical way of connecting the switcher would be with a `:*=` connection.
Without this change this will result in overlapping address spaces and fail in diplomacy.
> Update Switcher for rocket-chip Feb 14 2019

- src/main/scala/Switcher.scala
- src/main/scala/Unittests.scala
This should have gone in with the project template bigint-mems bump for large address spaces.
> Update switcher for large address spaces

- src/main/scala/NoDebug.scala
- src/main/scala/Switcher.scala
https://github.com/freechipsproject/rocket-chip/commit/4c5b38edbcd6eb12a342982c1fcd99ece550037d made dmi optional, and https://github.com/chipsalliance/rocket-chip/pull/1940 split the region type.
Needed for recent rocket-chip versions but will break with older ones.
> update for debug apb & regiontype in rocket-chip

- src/main/resources/testchipip/csrc/SimUART.cc
- src/main/resources/testchipip/csrc/uart.cc
- src/main/resources/testchipip/csrc/uart.h
- src/main/resources/testchipip/vsrc/SimUART.v
- src/main/scala/SerialAdapter.scala
- src/main/scala/UARTAdapter.scala
Adds a new trait that can be used in projects to create a UART and a corresponding UARTAdapter on the TestHarness side. By adding the plusarg `uartlog` you can create an output file(s) that gets the redirected `stdout`. I haven't tested in the `stdin` feature of this adapter but that was out of scope for this.
Todo:
> Add a UART Adapter

- src/main/scala/BlockDevice.scala
- src/main/scala/Configs.scala
- src/main/scala/SerialAdapter.scala
- src/main/scala/UARTAdapter.scala
- src/main/scala/Unittests.scala
Partnered to https://github.com/ucb-bar/chipyard/pull/347
- The new `CanHave` traits result in no-ops when `SerialKey` and `BlockDeviceKey` are set to a null value. (`SerialKey = false`, `BlockDeviceKey = None`)
- Users of these traits can mix this in to their default Top, and configure their behavior with the keys. I argue this is more elegant than the existing scheme of configuring the tops by manually cherry-picking traits.
> Refactor traits as CanHave traits

- src/main/scala/BlockDevice.scala
- src/main/scala/SerialAdapter.scala
- src/main/scala/UARTAdapter.scala
This takes the connect methods from SerialAdapter, BlockDevice, and UARTAdapter and puts them into objects so that they can be easily reused by Top and ChipTop (See ucb-bar/chipyard#480)
> Modularize connect methods

- src/main/scala/Generator.scala
- src/main/scala/SimDRAM.scala
- src/main/scala/TraceIO.scala
- src/main/scala/UARTAdapter.scala
- src/main/scala/Unittests.scala
> Stage Phase Rocket Chip Bump

- src/main/resources/testchipip/vsrc/ClockUtil.v
- src/main/scala/Configs.scala
- src/main/scala/Generator.scala
- src/main/scala/TestHarness.scala
- src/main/scala/Unittests.scala
This removes the unnecessary Generator/TestHarness, as we can use a separate generator/harness in chipyard for unit-testing all packages.
Also fixes the ClockUtilTests blackboxes so that it can work in VCS. Unfortunately, they won't work in verilator because it doesn't support the delay primitive.
> Delete Generator/TestHarness and fix ClockUtilTests

- README.md
- src/main/resources/testchipip/vsrc/ClockUtil.v
- src/main/scala/ClockUtil.scala
- src/main/scala/ClockUtilTests.scala
This removes the redundant `ClockGater` blackbox in testchipip and replaces it with the `ClockGate` set of APIs from rocket-chip.
> Use rocket-chip's ClockGate API to reduce reduncancy

- src/main/scala/Dromajo.scala
- src/main/scala/TraceIO.scala
This moves the Dromajo header code into a helper object and cleans up the TraceIO code a bit so that there are no more 1.B wires.
> Dromajo + TraceIO Cleanup

- src/main/resources/testchipip/csrc/SimDRAM.cc
- src/main/resources/testchipip/csrc/mm_dramsim2.h
This avoid the need to symlink the dramsim_ini directory everywhere.
This also maintains the default behavior if people still want to use that.
> Add constructor and parser for a dramsim ini directory from the cmd line

- src/main/scala/BlockDevice.scala
- src/main/scala/SerialAdapter.scala
Let's put this in after the RC bump is concluded.
> BlockDevice and SerialAdapter require minLatency > 0 (Fix Issue #88)

- src/main/resources/testchipip/csrc/SimDRAM.cc
- src/main/resources/testchipip/csrc/mm.cc
- src/main/resources/testchipip/csrc/mm.h
This is a less aggressive change than the other one. Instead of attempting to load the executable directly into memory, the user can provide a separate hex file to be loaded into a specified address. This way, SimSerial and SimDRAM don't need to be tied together. 
As a bonus, this also fixes an issue with dramsim_ini_dir not working if there are multiple SimDRAM channels.
> Implement loadmem functionality

- src/main/scala/Configs.scala
For configs with l2banks = 0, there is no MBUS to hang the dummy memory off of. In that case, hang it off the PBUS.
> Add config to hang the serial TL mem off the PBus for the no-L2 case.

- src/main/scala/Configs.scala
- src/main/scala/SerialAdapter.scala
- src/main/scala/Util.scala
This breaks the assumption that the client and slave sides of TLSerial are int the same clock domain, instead, TLSerial couples itself to the client domain, and provides a hook to select the manager-side crossing type. 
As in #103, provides ClockedAndResetIO.
The changes contained within are probably desirable even if we don't like chipyard-side changes.
> Add Support for MBUS crossings

- src/main/scala/BlockDevice.scala
- src/main/scala/ClockUtil.scala
- src/main/scala/ClockUtilTests.scala
- src/main/scala/HeaderEnum.scala
- src/main/scala/NoDebug.scala
- src/main/scala/Ring.scala
- src/main/scala/Serdes.scala
- src/main/scala/Switcher.scala
- src/main/scala/Unittests.scala
- src/main/scala/Util.scala
**Type of change**: paying off technical debt
**Impact**: no functional change
**What was changed**
fix compile warnings:
```
[warn] /testchipip/src/main/scala/HeaderEnum.scala:10:103: postfix operator mkString should be enabled
[warn] by making the implicit value scala.language.postfixOps visible.
[warn] This can be achieved by adding the import clause 'import scala.language.postfixOps'
[warn] or by setting the compiler option -language:postfixOps.
[warn] See the Scaladoc for value scala.language.postfixOps for a discussion
[warn] why the feature should be explicitly enabled.
[warn]     h.toSeq.sortBy(_._2).map { case (n,i) => s"#define ${prefix.toUpperCase}_${n.toUpperCase} $i\n" } mkString
[warn] …
```
> fix Scala Chisel compile deprecation warnings

- src/main/scala/TileResetCtrl.scala
fixes #110 
@jerryz123 and @davidbiancolin I'm going to bump RC in a clone of chipyard and try doing some FireSim builds.  Please let me know if there's something specific that will test that the TLTileResetCtrl is working as intended.
@hcook if you have a chance to take a look at this and see if it makes sense.  It compiles but I have a feeling that I might be missing something here.
> Teach TLTileResetCtrl about TileResetDomain

- src/main/scala/BlockDevice.scala
- src/main/scala/HeaderEnum.scala
**Related issue**: follow-on to https://github.com/ucb-bar/testchipip/pull/108
**Type of change**: paying off technical debt
**Impact**: no functional change
**What was changed**
fix compile warnings:
```
[warn] /testchipip/src/main/scala/BlockDevice.scala:433:3: method setResource in trait HasBlackBoxResource is deprecated (since 3.2): Use addResource instead
[warn]   setResource("/testchipip/vsrc/SimBlockDevice.v")
[warn]   ^
[warn] /testchipip/src/main/scala/BlockDevice.scala:434:3: method setResource in trait HasBlackBoxResource is deprecated (since 3.2): Use addResource instead
[warn]   setResource("/testchipip/csrc/SimBlockDevice.cc")
[warn]   ^
[warn] /testchipip/src/main/scala/BlockDevice.scala:435:3: method setResource in trait HasBlackBoxResource is deprecated (since 3.2): Use …
```
> Chisel deprecated: setResource -> addResource

- src/main/resources/testchipip/csrc/mm_dramsim2.h
in firesim/firesim#764 MIDAS-level simulation has been timing out.  This
is being caused by uninitialized value of clock_hz.  In general all
non-static data members should be given default member initializers
to guard against cases like this where several of the constructor
signatures of mm_dramsim2_t fail to initialize clock_hz.
> add default member initializer for mm_dramsim2_t::clock_hz

- src/main/scala/TraceIO.scala
I have a need to mix the trait CanHaveTraceIOModuleImp into another trait that extends LazyRawModuleImp.  This method of generalizing the definition was suggested to me and seems to work with both normal and raw lazy modules.
> Generalize CanHaveTraceIOModuleImp to mix in with LazyRawModuleImp

- src/main/resources/testchipip/csrc/testchip_tsi.h
testchip_tsi.cc throws an exception defined in <stdexcept> without it being
defined. add the missing import
> import <stdexcept> in testchip_tsi

- src/main/resources/testchipip/csrc/SimSerial.cc
- src/main/resources/testchipip/csrc/testchip_tsi.h
According to https://github.com/ucb-bar/chipyard/issues/1081 and per @jerryz123 's suggestion, I remove the VCS simv option from argv before entering base htif constructor. It is tested under chipyard. 
Command like `make EXTRA_SIM_FLAGS="-fgp=num_threads:2 -Xdprof=timeline"` will enable multi-thread VCS simulation via two step flow:
```
% vcs -fgp -full64 <otherOptions> 
% simv -fgp=num_threads:<value>
```
Additionally, a minor fix mentioned https://github.com/ucb-bar/testchipip/pull/134 due to compilation error.
> Support multi-thread VCS simv option like FGP, Xprof etc.

- src/main/resources/testchipip/csrc/testchip_tsi.h
Switch to the target thread when `htif` `idle`s. This enables continual execution of the target even if htif isn't working correctly.
> Idle tsi in the target thread.

- src/main/resources/testchipip/csrc/mm.cc
For 64B words the resulting strobe is 0, because the mask generation shifts out of bounds.
> mm: fix strb adjustment for 64B word sizes

- src/main/resources/testchipip/vsrc/SimSerial.v
- src/main/scala/SerialAdapter.scala
This ensures simulations will exit when TSI signals an error condition. For context, see https://github.com/ucb-bar/chipyard/issues/1283.
> Fail simulation upon TSI errors

- src/main/scala/BlockDevice.scala
- src/main/scala/SerialAdapter.scala
- src/main/scala/Unittests.scala
- src/main/scala/Util.scala
People should just construct nodes explicitly.
Using TLHelper is a bad pattern, it obscures the actual implementation and provides minimal benefit. It also encourages dependencies on testchipip-as-a-package, which is burdensome to support.
> Remove TLHelper

- src/main/resources/testchipip/csrc/testchip_tsi.cc
- src/main/resources/testchipip/vsrc/SimUART.v
* need defaults for verilog params (I only fixed the ones I tested in my design)
* need to pass binary using +binary= because sim tool will consume any args not prefixed with +/- and try to read them for its own purposes
> fixes for xcelium

- src/main/resources/testchipip/csrc/SimUART.cc
- src/main/resources/testchipip/csrc/testchip_tsi.cc
- src/main/resources/testchipip/csrc/testchip_tsi.h
- src/main/resources/testchipip/csrc/uart.cc
- src/main/resources/testchipip/csrc/uart.h
- src/main/resources/testchipip/vsrc/SimUART.v
- src/main/scala/Configs.scala
- src/main/scala/SerialAdapter.scala
- src/main/scala/UARTAdapter.scala
- uart_tsi/Makefile
- uart_tsi/testchip_uart_tsi.cc
- uart_tsi/testchip_uart_tsi.h
A PC host running the special `uart-tsi` fesvr implementation can communicate with a serial-adapter on a FPGA prototype or FPGA bringup-platform via UART.
Changes:
- Allows forcing the SimUART DPI thing to put the UART on a pty
- Fixes missing initialization of `is_loadmem` for testchip_tsi_t
- Fixes bytes getting dropped out of the SimUART FIFO
Adds:
- UART-to-TSI widget - intended for implementation on a FPGA board
- `uart-tsi` FESVR implementation, tsi commands are sent out over a TTY
Usage examples:
Running a program
```
>  ./uart_tsi +tty=/dev/ttyUSB1 dhrystone.riscv
Attempting to open TTY at /dev/ttyUSB1
Constructed uart_tsi_t
Checking connection status with /dev/ttyUSB1
Connection succeeded
Microseconds for one run through Dhrystone: 452
Dhrystones per Second: …
```
> TSI-over-UART

- src/main/scala/SimTLMem.scala
Add a SimTLMem which can be used in the simulation TestHarness when using a TL punch through
> Add SimTLMem

- uart_tsi/testchip_uart_tsi.cc
Depending on some combination of {Kernel Version, UART Adapter}, the default value of the size field will get set to values other than 8 by default. The C code expects this and tries to manually set the `size = 8` flag, but does so by AND-ing the old flag with the new flag, which doesn't work because boolean logic.
Tested working on an [Terasic Apollo Agliex SOM](https://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&No=1278) and verified via Signal Tap (logic analyzer).
> fix(uart-tsi): use |= to set flag instead of &=

- src/main/resources/testchipip/csrc/SimUART.cc
- src/main/resources/testchipip/vsrc/SimUART.v
- src/main/scala/UARTAdapter.scala
- Fixes multi-uart designs, now the multiple uarts are independent, while previously, they were all multiplexed off the same thing
- Allows forcePTY, which forces a SimUART to send the UART out to a pty
Note that this does not require a Chipyard bump, since APIs are unchanged. To avoid more churn in chipyard, I'll just open the PR here, and the next testchipip bump in chipyard will pick up these changes too.
> Fix Multi-UART | add ForcePTY

- src/main/scala/SerialAdapter.scala
Generate the clock off-chip, instead of relying on the on-chip clock
> Flip serialized tilelink clock source

- src/main/scala/BootAddrReg.scala
- src/main/scala/Configs.scala
- src/main/scala/CustomBootPin.scala
Previously, BootAddrReg was always present on all designs.
It doesn't make since to add this to designs with no cores, so make this an optional device intsead.
> Make BootAddrReg an optionally-enabled feature

- src/main/resources/testchipip/csrc/SimDRAM.cc
- src/main/resources/testchipip/csrc/mm.cc
- src/main/resources/testchipip/csrc/mm.h
- src/main/resources/testchipip/csrc/mm_dramsim2.cc
- src/main/resources/testchipip/csrc/mm_dramsim2.h
- src/main/resources/testchipip/vsrc/SimDRAM.v
The old coder used `addr % size` to subtract out the DRAM base offset, but this doesn't work when DRAM is not aligned to the size.
Overall this makes `mm_t` more robust.
> Fix DRAMSim2 sign extension bug

- src/main/resources/testchipip/csrc/testchip_dtm.cc
- src/main/resources/testchipip/csrc/testchip_dtm.h
- src/main/resources/testchipip/csrc/testchip_htif.cc
- src/main/resources/testchipip/csrc/testchip_htif.h
- src/main/resources/testchipip/csrc/testchip_tsi.cc
- src/main/resources/testchipip/csrc/testchip_tsi.h
- src/main/scala/SimDTM.scala
- src/main/scala/SimTSI.scala
- uart_tsi/Makefile
This enables the `+init_read/+init_write/+no_hart0_msip` custom features for both dmi and tsi bringup.
> Pull common components of testchip_tsi/testchip_dtm into testchip_htif_t

- src/main/scala/TraceIO.scala
Using `trace.asTypeOf(serializable_trace.trace)` causes issues since `trace` isn't the same type as `serializable_trace` (i.e. the fields aren't in the same order across both bundles). This punches out the connections.
> Avoid direct serialization of trace

- src/main/scala/BlockDevice.scala
- src/main/scala/SPIFlash.scala
- src/main/scala/Unittests.scala
This brings the API in-line with the Port API in CY, which will not pass around Parameters from the SoC to the harness.
> Remove implicit Parameters from some harness blocks

- src/main/resources/testchipip/csrc/TestchipSimDTM.cc
- src/main/resources/testchipip/csrc/testchip_dtm.cc
- src/main/scala/SimDTM.scala
Matches what other debug interfaces (i.e. TSI) do. Needed so that C code that inherits from `testchip_dtm.*` but doesn't have VPI headers can compile.
> Split debug_tick from rest of code

- src/main/scala/ClockUtil.scala
- src/main/scala/Configs.scala
The Rocket-chip one sometimes doesn't include the resource file, ours always does
> Add config/class to instantiate our own EICG_wrapper

- src/main/scala/boot/CustomBootPin.scala
- src/main/scala/boot/TileResetCtrl.scala
- src/main/scala/cosim/Cospike.scala
- src/main/scala/iceblk/BlockDevice.scala
- src/main/scala/serdes/Adapter.scala
- src/main/scala/serdes/PeripheryTLSerial.scala
- src/main/scala/soc/OffchipBus.scala
- src/main/scala/tsi/TSIHarness.scala
- src/main/scala/tsi/TSIToTileLink.scala
- src/main/scala/util/Util.scala
- `IO` was moved from `chisel3.experimental` to `chisel3`
- Calls to `fire` with empty parens need the parens removed
- `DataMirror` was moved from `chisel3.experimental` to `chisel3.reflect`
> Update deprecated APIs to prepare for Chisel 5

- src/main/scala/serdes/SerialPhy.scala
Add guard around outer interface to prevent accepting/transmit from/to the external world of TL serial interface. The chip now waits for the chip to come out of reset before driving the ready for the incoming data, and valid for the data coming from outside the chip to inside the chip.
> Bug fix; Simulation does not wait for chip to come out of reset

- src/main/resources/testchipip/csrc/cospike.cc
- src/main/resources/testchipip/csrc/cospike_impl.cc
- src/main/resources/testchipip/csrc/cospike_impl.h
- src/main/resources/testchipip/vsrc/cospike.v
- src/main/scala/cosim/Cospike.scala
This doesn't remove the legacy `mem0_base/size` field, so firesim+cosim will still work correctly.
At some point the next user of firesim+cosim may want to update the bridge to use the new API, but that can be done in the future.
> Improve cospike API for multiple memory regions

- src/main/resources/testchipip/csrc/SimDRAM.cc
- src/main/resources/testchipip/vsrc/SimDRAM.v
- src/main/resources/testchipip/vsrc/SimTSI.v
Masks of `mem_base` in `SimDRAM.cc` due to a sign extension bug. Also adds a default parameter value for `SimTSI`.
> Misc Xcelium fixes

- src/main/scala/serdes/TLSerdes.scala
The current warning:
[warn] generators/testchipip/src/main/scala/serdes/TLSerdes.scala 85:9: [W008] Return values of asTypeOf will soon be read-only
[warn]       c <> b.io.protocol
[warn]         ^
This warning becomes an error in Chisel 7.
More context on this change from Chisel:
- https://github.com/chipsalliance/chisel/pull/4198
- https://github.com/chipsalliance/chisel/blob/48f676b6009377655860ca71e6c008da31c8419a/docs/src/explanations/warnings.md?plain=1#L153
Adding a wire is the recommended fix from `warnings.md`.
> Resolve asTypeOf-is-read-only warning

- src/main/resources/testchipip/csrc/SimDRAM.cc
Xcelium doesn't support `svGetBitArrElemVecVal`, and segfaults when that function is executed. Using `svGetArrElemPtr1` should have the same behavior. It returns a pointer to the array element, rather than `svGetBitArrElemVecVal`, which returns a copy of the array element. Also `svGetBitArrElemVecVal` works with a wider variety of bit-array data types, whereas `svGetArrElemPtr1` seems more useful when the underlying datatype can be represented as a native C datatype. Luckily, the underlying SystemVerilog type here is `byte`.
> SimDRAM: Use svGetArrElemPtr1 instead of svGetBitArrElemVecVal
