csrc/blkdev.cc

Simple PR. will merge in a bit unless @zhemao says anything

eliminate compiler warnings blkdev

---

src/main/scala/BlockDevice.scala
src/main/scala/Unittests.scala

I didn't try this in vivo, but it at least compiles using the latest rocket-chip.

Remove IntIdentityNode; Use TL := operator thingy.

---

src/main/scala/Generator.scala

Revise src/main/scala/Generator.scala : address issue #13

fix for deprecated Parameters.root

---

build.sbt
src/main/scala/Serdes.scala

This has been tested on the FPGA in FireSim. See https://github.com/firesim/firesim/pull/113

Bump to match up with July 3, 2018 Rocket Chip

---

src/main/scala/Generator.scala

It's currently out of date and can cause casting errors

Import rocket's GeneratorApp directly instead of copying

---

Makefrag
src/main/scala/ClockUtil.scala
src/main/scala/ClockUtilTests.scala
src/main/scala/Unittests.scala
vsrc/ClockUtil.v

This adds some clock utilities that previously lived in eagle-pll, with some added withGatedClock(AndReset) objects and removed tech-specific implementations of the clock cells.

Add clock utilities

---

vsrc/ClockUtil.v

Fix for verilator (found testing project-template)

don't use (...); and instead use (...); ; for verilator support

---

src/main/scala/SerialAdapter.scala
src/main/scala/Switcher.scala
src/main/scala/Unittests.scala

Hopefully would be merged after https://github.com/ucb-bar/testchipip/pull/43 so they are just fastforwards

Serial adapter ids

---

src/main/scala/Serdes.scala
src/main/scala/Switcher.scala
src/main/scala/Unittests.scala

Have the SERDES take the max params of the client and the manager.

SERDES Fix

---

src/main/scala/BlockDevice.scala

This reverts commit 53c019a4925cef967a3b1cc6a51c7d74a9aa677f.

Revert "remove header from resources"

---

src/main/scala/BlockDevice.scala
src/main/scala/SerialAdapter.scala

See https://github.com/ucb-bar/chipyard/pull/207

Switch devices to use fbus for DMA and pbus for MMIO

---

src/main/scala/ClockUtil.scala
src/main/scala/Generator.scala
src/main/scala/NoDebug.scala
src/main/scala/Serdes.scala
src/main/scala/Unittests.scala
src/main/scala/Util.scala

Updates for rocket-chip and chisel 3.2.0 for chipyard see: ucb-bar/chipyard#358

Chisel update aug 2019

---

src/main/scala/BlockDevice.scala
src/main/scala/SerialAdapter.scala
src/main/scala/UARTAdapter.scala

Unbreak dev

---

src/main/scala/Configs.scala
src/main/scala/Ring.scala
src/main/scala/UARTAdapter.scala

See: https://github.com/ucb-bar/chipyard/pull/544

Rc 1.3 bump

---

src/main/scala/TraceIO.scala

Companion to https://github.com/ucb-bar/chipyard/pull/605

Bump Rocketchip to June 2020

---

build.sbt
project/build.properties

Related PR: ucb-bar/chipyard#719

Cleanup build.sbt | Bump versions

---

src/main/scala/Network.scala
src/main/scala/TraceIO.scala
src/main/scala/Unittests.scala

To fix the errors in https://github.com/chipsalliance/chisel3/pull/2751.

fix: S-interpolator for assert, assume and printf

---

src/main/resources/testchipip/csrc/blkdev.cc
src/main/resources/testchipip/csrc/plusarg_file_mem.cc

add cstdio to include

---

src/main/scala/ClockUtil.scala

`ClockDivider` can be parameterized to reset with a active clock out, instead of gating it. 
`ClockDividerOrPass` now is a RawModule, so users have to be explicit in specifying what clock is being divided
`io.divisor` in `ClockDividerOrPass` is now sync'd to the clock it is dividing, as it should be.

Improvements to clock dividers

---

src/main/scala/BlockDevice.scala
src/main/scala/Unittests.scala

This fixes compile with latest rocket-chip

Add DontCares explicitly

---

src/main/resources/testchipip/csrc/cospike_impl.cc

Print fixes and remove extra includes

---

src/main/resources/testchipip/csrc/cospike_impl.cc

Related to ucb-bar/chipyard#1692

bump spike to latest

---

src/main/resources/testchipip/csrc/cospike.cc
src/main/resources/testchipip/csrc/cospike_impl.cc
src/main/resources/testchipip/csrc/cospike_impl.h
src/main/resources/testchipip/vsrc/cospike.v
src/main/scala/cosim/Cospike.scala

Handy for designs with scratchpad regions

Support multiple base memory regions

---

src/main/scala/serdes/Serdes.scala

Note, #228 didn't introduce a functional bug, it just broke chisel3 compile. This fixes chisel3 compile.

Fix serdes PhitArbiter widths, fixes bug introduced in #228

---

uart_tsi/testchip_uart_tsi.cc
uart_tsi/testchip_uart_tsi.h

* Binary loading is now bursty, instead of buffering all the bytes in memory before sending any, it streams chunks into the targe
* Self-check is now per-chunk, instead of once at the end of the binary

Improve testchip_uart_tsi

---

src/main/scala/serdes/Bundles.scala
src/main/scala/serdes/Configs.scala
src/main/scala/serdes/Parameters.scala
src/main/scala/serdes/PeripheryTLSerial.scala
src/main/scala/serdes/SerialPhy.scala
src/main/scala/test/Unittests.scala

Describe both flow control and clocking in the naming

Improve naming of SerialPhyParams

---

src/main/resources/testchipip/csrc/SimDRAM.cc

fixes verilator segfault by gating array read and using a different API for writing

Fix verilator segfault

---

src/main/resources/testchipip/csrc/SimDRAM.cc
src/main/resources/testchipip/vsrc/SimDRAM.v

FIx the fix that fixes the segfault

---

src/main/scala/serdes/SerialPhy.scala

The AsyncQueue must use a synchronous reset, but these ports can use the generic reset type.
Required for https://github.com/ucb-bar/chipyard/pull/2248

Support connections from generic reset inputs
